services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:1.2.0
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 5
      AUTOHEAL_START_PERIOD: 0
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 10
      AUTOHEAL_ONLY_MONITOR_RUNNING: false
      DOCKER_SOCK: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
