services:
  kavita:
    image: jvmilazz0/kavita:0.8.4
    container_name: kavita
    volumes:
      - /mnt/storage/kavita:/books
      - ./data:/kavita/config
    environment:
      - TZ=Europe/Paris
    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.rule=Host(`${COMPOSE_PROJECT_NAME}.local.tellserv.fr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.entryPoints=local"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.tls.certresolver=cloudflare-local"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.rule=Host(`${COMPOSE_PROJECT_NAME}.tellserv.fr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.entryPoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.tls.certResolver=cloudflare"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5000"
      - "com.centurylinklabs.watchtower.enable=true"

  kavita-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kavita-watcher
    volumes:
      - /mnt/storage/kavita:/mnt/storage/kavita
    environment:
      - TZ=Europe/Paris
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - traefik_network
    restart: unless-stopped

networks:
  traefik_network:
    external: true
