services:
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true
      - TZ=Europe/Paris
    volumes:
      - "/mnt/storage/pingvin:/opt/app/backend/data"
      - "/mnt/storage/pingvin/images:/opt/app/frontend/public/img"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      # Local
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.rule=Host(`${COMPOSE_PROJECT_NAME}.local.tellserv.fr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.entryPoints=local"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.tls.certresolver=cloudflare-local"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.tls=true"
      # Production
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.rule=Host(`${COMPOSE_PROJECT_NAME}.tellserv.fr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.entryPoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-prod.tls.certResolver=cloudflare"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

      # Flame Dashboard Integration

      # Watchtower Auto-Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik_network:
    external: true
