http:
  routers:
    cockpit-rtr:
      rule: "Host(`cockpit.local.tellserv.fr`)"
      entryPoints:
        - local
      service: cockpit-svc
      tls:
        certResolver: cloudflare-local
      middlewares:
        - cockpit-headers

  services:
    cockpit-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://host.docker.internal:9090"

  middlewares:
    cockpit-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Port: "443"
