http:
  middlewares:
    ratelimit:
      rateLimit:
        average: 100
        burst: 50
        period: 1s
    secheaders:
      headers:
        stsSeconds: 31536000
        forceSTSHeader: true
    evasive:
      rateLimit:
        average: 3
        burst: 5
        period: 1s
    localonly:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
          - "100.64.0.0/10"
          - "172.18.0.0/16"
