http:
  routers:
    proxmox-rtr:
      rule: "Host(`proxmox.local.tellserv.fr`)"
      entryPoints:
        - local
      service: proxmox-svc
      tls:
        certResolver: cloudflare-local
      middlewares:
        - proxmox-headers

  services:
    proxmox-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "https://192.168.1.29:8006"

  middlewares:
    proxmox-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Port: "443"
